### ISSUE TITLE
uboot binary has switch reversed

### ISSUE THREAD

**Issue by cyablo** [gl-inet/uboot-for-qca95xx#1]
Check out this forum thread: https://forum.gl-inet.com/t/updated-u-boot-for-ar300m-not-booting-oses/4906/18

The binary you provide has the boot selection switch reversed to that booting from NOR is only possible withe the case removed.

**Comment by kysonlok** [comment]
If you slide it to left, it doesn't boot from nand?

**Comment by cyablo** [comment]
Fixed in newer bootloader.

**Comment by cyablo** [comment]
Did the newest bootloader remove the switch NOR/NAND boot feature? My AR300M is laways booting into NAND, even with bootcount 3 or boot_dev set.

**Comment by cyablo** [comment]
Uboot now has option to enable switch in web interface. Seems to be new, ddn't know that.
